name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Awesome, You have raised the first issue'' first issue'
        pr-message: 'Thank you for Caring about the project,Heres your First Pull Request'' first pr'
